version: '3'

services:
  nginx:
    image: nginx:1.23.3-alpine-slim
    container_name: nginx
    ports:
      - "8082:80"
    volumes:
      - ./your_app:/var/www/html:z
      - ./nginx/conf.d:/etc/nginx/conf.d/:z
    depends_on:
      - php74

  php74:
    image: php:7.4.33-fpm-alpine3.16
    ports:
      - "9000:9000"
    restart: unless-stopped
    user: 1000:1000
    container_name: php74
    volumes:
      - ./your_app:/var/www/html:z
      - ./php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:z
  # uncommit this lines if you need mysql
  # db:
  #   image: mysql:5.7
  #   container_name: db
  #   restart: always
  #   environment:
  #     - "MYSQL_DATABASE=laravel"
  #     - "MYSQL_USER=root"
  #     - "MYSQL_PASSWORD=secret"
  #     - "MYSQL_ROOT_PASSWORD=secret"
  #   volumes:
  #     - dbdata:/var/lib/mysql
  # uncommit this lines if you need phpmyadmin
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin
  #   restart: always
  #   ports:
  #     - "8081:80"
  #   environment:
  #     - "PMA_HOST=db"
  #     - "MYSQL_USER=root"
  #     - "MYSQL_PASSWORD=secret"
  # volumes:
  #   dbdata:

