version: '3'

services:
  nginx:
    image: nginx:1.23.3-alpine-slim
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ./your_app:/var/www/html:z
      - ./nginx/conf.d:/etc/nginx/conf.d/:z
    depends_on:
      - php74
    networks:
      - default   
      
  php74:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./your_app:/var/www/html:z

    # Set environment variables for PHP
    environment:
      PHP_FPM_HOST: php74
      PHP_FPM_PORT: "9000"
    networks:
      - default
  # uncommit this lines if you need mysql
  # db:
  #   image: mysql:5.7
  #   container_name: db
  #   restart: always
  #   environment:
  #     - "MYSQL_DATABASE=laravel"
  #     - "MYSQL_USER=root"
  #     - "MYSQL_PASSWORD=secret"
  #     - "MYSQL_ROOT_PASSWORD=secret"
  #   volumes:
  #     - dbdata:/var/lib/mysql
  # uncommit this lines if you need phpmyadmin
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin
  #   restart: always
  #   ports:
  #     - "8081:80"
  #   environment:
  #     - "PMA_HOST=db"
  #     - "MYSQL_USER=root"
  #     - "MYSQL_PASSWORD=secret"
  # volumes:
  #   dbdata:

networks:
  default:
    external:
      name: nginx_proxy
